name: Python Application Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8  # Use the version of Python you're developing with

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover

    - name: Run the Flask app (for testing purposes)
      run: |
        nohup python app.py &
        sleep 10  # Allow time for the app to start

    - name: Check if Flask is running
      run: curl -I http://127.0.0.1:3000

